### ISSUE TITLE
Unable to use own cypress.json

### ISSUE THREAD

**Issue by jlnschfr** [factorial-io/fstack#15]
it's not possible to have a project specific cypress.json as mentioned in the docs.

It seems that the config is not getting passed properly to the `run` method as described here
https://docs.cypress.io/guides/guides/module-api

see https://github.com/factorial-io/fstack/blob/main/packages/e2e/lib/test.js

**Comment by mgrsskls** [comment]
It is working fine, but we don't merge the `config` object, we merge the whole object. So, instead of only passing your `config` object, you need to pass an object, which contains a `config` key with your object as its value.

I will update the README here and close this for now. Feel free to reopen it if this doesn't work for you!
